project:
  type: website
  render:
    - "*.{qmd,R,py}"
    - "!utils.py"

website:
  title: "fastai-projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



